### ISSUE TITLE
What are the differences and the commonalities?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [KeitaNakamura/Tensorial.jl#157]
Would it be possible to summarize, perhaps in the README, the differences and commonalities of the present package and comparable tensor packages?

**Comment by KeitaNakamura** [comment]
Hi. There are several packages for tensor operations, but I only have experience using [Tensors.jl](https://github.com/Ferrite-FEM/Tensors.jl) and [TensorOperations.jl](https://github.com/Jutho/TensorOperations.jl). So, I mainly mention about the differences and commonalities with these two packages below. 

I had used `Tensors.jl` package for a long time and had contributed to it a bit before. It is a great package (very fast, useful symbolic tensor operations such as contraction `⋅`, tensor product `⊗`, etc.). Especially, I love symbolic operations. But...

### Rank and dimension

`Tensors.jl` can only handle `1`, `2` and `4` rank tensors (for now), and those vector spaces must be the same dimension such as `3x3` tensor, `2x2` tensor, or `3x3x3x3` tensor. The dimension is also restricted to `1`, `2` or `3` except for the vector type `Vec` (maybe?). I know that those tensors are very common in use, but in some cases, I want to use `3x2` tensor, `3x4` tensor, `3x3x3` tensor, etc.
In such cases, I need to manually convert the tensors to the static arrays in [StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl), perform some operations, and then convert them back to tensors again. I was sick of doing this process. So, I created this package. In `Tensorial.jl`, there are no restrictions for rank and dimensions. If you don’t care the symmetries, a way to construct the tensors is almost the same as `StaticArrays.jl`. But, like as `StaticArrays.jl`, normal `Array`s are preferred for arrays larger than roughly 100 elements.

### Symmetry

For the fast computations and correct automatic differentiations, we need to handle symmetries properly. So, considering symmetries are very important in tensor operations. This feature is also supported in `Tensors.jl`, but `Tensorial.jl` can represent symmetric tensors in more flexible manner. You can apply `@Symmetry` to any adjacent indices. Symmetric fourth order tensor (symmetrizing tensor) can be simply given as `@Tensor{@Symmetry{3,3}, @Symmetry{3,3}}`, where `@Tensor` can omit annoying `Tuple` like `Tensor{Tuple{@Symmetry{3,3}, @Symmetry{3,3}}}`. `@Tensor{@Symmetry{3,3}, 3,3}` also just works if you want.

### Einstein's summation convention

Another key feature in `Tensorial.jl` is `@einsum` to perform Einstein’s summation convention. I think `TensorOperations.jl` package mainly focuses on this and is optimized for relatively large size of arrays (maybe?). This Einstein’s convention is useful in some cases such as `v[k] * S[i,k,j,l] * w[l]`. Although this operation is provided as `dotdot(v, S, w)` function in `Tensors.jl`, using Einstein’s convention is more intuitive like `@einsum (i,j) -> v[k] * S[i,k,j,l] * w[l]` and we don’t need to define special functions anymore. The speed is also fast

#### Tensors.jl v1.9.1
```julia
julia> using Tensors, BenchmarkTools

julia> S = rand(SymmetricTensor{4,3}); v = rand(Vec{3}); w = rand(Vec{3});

julia> @btime dotdot($(Ref(v))[], $(Ref(S))[], $(Ref(w))[]);
  19.398 ns (0 allocations: 0 bytes)

julia> A = rand(SymmetricTensor{2,3}); B = rand(SymmetricTensor{2,3});

julia> @btime otimesu($(Ref(A))[], $(Ref(B))[]); # @einsum (i,j,k,l) -> A[i,k] * B[j,l]
  15.987 ns (0 allocations: 0 bytes)

julia> @btime otimesl($(Ref(A))[], $(Ref(B))[]); # @einsum (i,j,k,l) -> A[i,l] * B[j,k]
  15.980 ns (0 allocations: 0 bytes)
```

#### Tensorial.jl v0.11.6
```julia
julia> using Tensorial, BenchmarkTools

julia> S = rand(@Tensor{@Symmetry{3,3}, @Symmetry{3,3}}); v = rand(Vec{3}); w = rand(Vec{3});

julia> @btime @einsum (i,j) -> $(Ref(v))[][k] * $(Ref(S))[][i,k,j,l] * $(Ref(w))[][l];
  10.816 ns (0 allocations: 0 bytes)

julia> A = rand(@Tensor{@Symmetry{3,3}}); B = rand(@Tensor{@Symmetry{3,3}});

julia> @btime @einsum (i,j,k,l) -> $(Ref(A))[][i,k] * $(Ref(B))[][j,l];
  15.986 ns (0 allocations: 0 bytes)

julia> @btime @einsum (i,j,k,l) -> $(Ref(A))[][i,l] * $(Ref(B))[][j,k];
  9.379 ns (0 allocations: 0 bytes)
```

The benchmarks are performed on

```Julia
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Xeon(R) W-3275M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)
```

### Broadcast

For the broadcast operations, tensors in `Tensorial.jl` behave like scalars rather than arrays. So we can write

```Julia
julia> x = Vec(1,2,3)
3-element Vec{3, Int64}:
 1
 2
 3

julia> V = [Vec{3}(i:i+2) for i in 1:4]
4-element Vector{Vec{3, Int64}}:
 [1, 2, 3]
 [2, 3, 4]
 [3, 4, 5]
 [4, 5, 6]

julia> x .+ V
4-element Vector{Vec{3, Int64}}:
 [2, 4, 6]
 [3, 5, 7]
 [4, 6, 8]
 [5, 7, 9]

julia> V .= zero(x)
4-element Vector{Vec{3, Int64}}:
 [0, 0, 0]
 [0, 0, 0]
 [0, 0, 0]
 [0, 0, 0]
```

This is inspired by [Gridap.jl](https://github.com/gridap/Gridap.jl).

The differences and commonalities are roughly like this. In addition, statically sized `getindex` (`@Tensors S[1:2,1:2]` returns `@Tensor{@Symmetry{2,2}}`), `vcat/hcat/hvcat` are also implemented to feel like *it just works*.

**Comment by KeitaNakamura** [comment]
I summarized as table:

| Features | Tensorial.jl | Tensors.jl | TensorOperations.jl | StaticArrays.jl |
| :--------|:---------:|:--------:|:-----------------:|:-------------:|
| Statically-sized arrays | Yes | Yes | No | Yes |
| Good for large arrays | No | No | Yes | No |
| Arbitrary size arrays | Yes | No | Yes | Yes |
| Symbolic tensor operations | Yes | Yes | No | No |
| Einstein's convention | Yes | No | Yes | No |
| Symmetry | Yes | Yes | N/A | N/A |

From the table, `Tensorial.jl` looks very good, but I don't want to say that. For me, the implementation in `Tensors.jl` is very simple and sophisticated. So, I think that `Tensors.jl` is much suit to people who don't need the arbitrary size of tensors. This package is basically developed for my own research.

**Comment by PetrKryslUCSD** [comment]
Fantastic! Thank you very much, very useful.

**Comment by PetrKryslUCSD** [comment]
How to the compilation times compare?

**Comment by KeitaNakamura** [comment]
**Tensors.jl v1.9.1**

```Julia
julia> @time using Tensors
  1.181997 seconds (3.36 M allocations: 239.320 MiB, 3.85% gc time, 21.83% compilation time)

julia> @time x = rand(Tensor{2,3});
  0.000001 seconds (1 allocation: 80 bytes)

julia> @time y = rand(SymmetricTensor{2,3});
  0.000001 seconds (1 allocation: 64 bytes)

julia> @time x ⋅ y;
  0.174643 seconds (302.47 k allocations: 16.647 MiB, 15.76% gc time, 99.92% compilation time)

julia> @time x ⊡ y;
  0.081426 seconds (286.88 k allocations: 15.876 MiB, 99.93% compilation time)

julia> @time x ⊗ x;
  0.210905 seconds (825.89 k allocations: 43.047 MiB, 19.11% gc time, 99.97% compilation time)

julia> @time y ⊗ y;
  0.077549 seconds (316.65 k allocations: 17.111 MiB, 99.95% compilation time)
```

**Tensorial.jl v0.11.6**

```Julia
julia> @time using Tensorial
  1.085362 seconds (3.23 M allocations: 226.519 MiB, 4.15% gc time, 23.00% compilation time)

julia> @time x = rand(@Tensor{3,3});
  0.000001 seconds (1 allocation: 80 bytes)

julia> @time y = rand(@Tensor{@Symmetry{3,3}});
  0.000001 seconds (1 allocation: 64 bytes)

julia> @time x ⋅ y;
  2.099631 seconds (6.97 M allocations: 390.957 MiB, 14.64% gc time, 100.00% compilation time)

julia> @time x ⊡ y;
  0.122276 seconds (438.20 k allocations: 25.073 MiB, 99.99% compilation time)

julia> @time x ⊗ x;
  0.669818 seconds (2.32 M allocations: 123.749 MiB, 4.18% gc time, 100.00% compilation time)

julia> @time y ⊗ y;
  0.299285 seconds (920.60 k allocations: 50.183 MiB, 4.53% gc time, 99.99% compilation time)
```

The complication time in `Tensors.jl` is much faster than `Tensorial.jl` especially the first run of contraction. But `Tensorial.jl` uses almost the same functions for all kinds of contractions (single, double, tensor product, etc), so once you run the `⋅`, compilation times for `⊡` and `⊗` become a bit faster.
